//Compares two file Expected output and output generated by you code

#include <iostream>
#include <fstream>          //fstream library
#include <string.h>

using namespace std;

bool strMatch(char s1[], char s2[], char s3[])
{
    bool isMatch = 1;
    int i = 0;

    for( ; s1[i] != '\0' || s2[i] != '\0'; i++) {
        if(s1[i] == s2[i])
            s3[i] = ' ';
        else {
            s3[i] = '^';
            isMatch = 0;
        }
    }

    if(s1[i] == '\0' && s2[i] != '\0') {
        isMatch = 0;
        for( ; s2[i] != '\0'; i++) {
            s3[i] = '^';
            s1[i] = ' ';
        }
    }
    else if(s1[i] != '\0' && s2[i] == '\0') {
        isMatch = 0;
        for( ; s1[i] != '\0'; i++) {
            s3[i] = '^';
            s2[i] = ' ';
        }
    }

    s3[i] = '\0';

    return isMatch;
}

int main()
{
    fstream file1, file2;
    string origFile, cmpFile, input;
    bool isMatched = 1;

    //this line sets input output file built-in
    //origFile = "ans", cmpFile = "";
    cout << "Enter two files to compare (Expected answer file, output generated by code) : ";
    cin >> origFile >> cmpFile;

    file1.open(origFile, ios::in);
    file2.open(cmpFile, ios::in);

    if(!file1.is_open() || !file2.is_open()) {
        cout << "File not found! \nQuitting\n";
        return 1;
    }
    else {
        int lineCount = 1;
        char s1[1000010], s2[1000010], s3[1000010];

        while(!file1.eof() && !file2.eof()) {
            file1.getline(s1, 1000000);
            file2.getline(s2, 1000000);
            if(!strMatch(s1, s2, s3)) {
                if(isMatched == 1)
                    cout << "Mismatches : WA -||- AC" << endl;
                cout << "Line : " << lineCount << endl;
                cout << s2 << " -||- " << s1 << endl;
                cout << s3 << endl;
                isMatched = 0;
            }
            memset(s1, 0, sizeof s1);
            memset(s2, 0, sizeof s2);
            memset(s3, 0, sizeof s3);
            s1[0] = s2[0] = s3[0] = '\0';
            lineCount++;
        }

        while(!file1.eof()) {
            if(isMatched == 1)
                cout << "Mismatches : WA -||- AC" << endl;
            file1.getline(s1, 1000000);
            strMatch(s1, s2, s3);
            cout << s2 << " -||- " << s1 << endl;
            cout << s3 << endl;
            lineCount++;
            memset(s1, 0, sizeof s1);
            memset(s2, 0, sizeof s2);
            memset(s3, 0, sizeof s3);
            s1[0] = s2[0] = s3[0] = '\0';
            isMatched = 0;
        }

        while(!file2.eof()) {
            if(isMatched == 1)
                cout << "Mismatches : WA -||- AC" << endl;
            file2.getline(s2, 1000000);
            strMatch(s1, s2, s3);
            cout << s2 << " -||- " << s1 << endl;
            cout << s3 << endl;
            lineCount++;
            memset(s1, 0, sizeof s1);
            memset(s2, 0, sizeof s2);
            memset(s3, 0, sizeof s3);
            s1[0] = s2[0] = s3[0] = '\0';
            isMatched = 0;
        }
    }

    if(isMatched)
        cout << "Fully Matched!" << endl;
    return 0;
}
